name: Build and Deploy WebUI

on:
  push:
    branches: [ "preston" ]
#   pull_request:
#     branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Build and Deploy React app to GitHub Pages
      uses: omkartapale/react-deployment-gh-pages@v1.0.0